security:
  encoders:
    App\Entity\Utilisateur:
      algorithm: bcrypt
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: emailU
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      provider: app_user_provider
      form_login:
        login_path: login
        check_path: login
        default_target_path: /homepage # Redirect to the homepage after login
      logout:
        path: logout
        target: /
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 week
  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/homepage, roles: ROLE_USER }
