security:
  encoders:
    App\Entity\Utilisateur:
      algorithm: bcrypt
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: emailU
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      provider: app_user_provider
      form_login:
        login_path: login
        check_path: login
        default_target_path: /homepage # Redirect to the homepage after login
        target_path_parameter: _target_path
        success_handler: App\Controller\Security\CustomAuthenticationSuccessHandler
      logout:
        path: logout
        target: /
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 week
      two-factor:
        auth_form_path: 2fa_login
        check_path: 2fa_login_check
        default_target_path: /homepage
  access_control:
    # This makes the logout route accessible during two-factor authentication. Allows the user to
    # cancel two-factor authentication, if they need to.
    - { path: ^/logout, role: PUBLIC_ACCESS }
    # This ensures that the form can only be accessed when two-factor authentication is in progress.
    - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/homepage, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
