#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
register:
  path: /register
  controller: App\Controller\SecurityController::register
logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
my_questions:
  path: /my-questions
  controller: App\Controller\QuestionController::myQuestions
  methods: GET
