<<<<<<< Updated upstream
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
=======
landingpage:
  path: /
  controller: App\Controller\LandingpageController::landingpage

login:
  path: /login
  controller: App\Controller\SecurityController::login

register:
  path: /register
  controller: App\Controller\SecurityController::register

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

homepage:
  path: /homepage
  controller: App\Controller\HomepageController::homepage
>>>>>>> Stashed changes
